version: '3'

services:
  postgres:
    image: 'postgres:11'
    container_name: sampleproject_db
    restart: always
    environment:
      POSTGRES_DB: sampleproject_db
      POSTGRES_USER: sampleproject_db_user
      POSTGRES_PASSWORD: sampleproject_db_pwd
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  django:
    build: .
    container_name: sampleproject_app
    restart: always
    command: >
      bash -c "python ./manage.py makemigrations &&
                ./manage.py migrate &&
               ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      - postgres

volumes:
  postgres_data:
